name: Build and Push Nuxt frontend.

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build-and-deploy-frontend:
    name: Build nuxt and deploy to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          push: true
          file: ./Dockerfile
          tags: ${{secrets.DOCKER_IMAGE}}
